name: deploy-vue-to-strato

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - show files
        run: |
          ls -la
          cat package.json

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Debug - show dist content
        run: |
          ls -la dist

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy dist folder to Strato
        run: |
          sshpass -p "${{ secrets.USER_PASSWORD }}" rsync -avz --delete --progress \
          -e "ssh -o StrictHostKeyChecking=no" \
          dist/ \
          ${{ secrets.USER }}@${{ secrets.USER_IP }}:${{ secrets.ABS_PATH }}
